title: catstret.ch
baseurl: ""
url: "https://catstret.ch"
permalink: "/:year:month/:title:output_ext"
excerpt_separator: <!--cut-->

kramdown:
  parse_block_html: true
  hard_wrap: false
  gfm_quirks:
    - paragraph_end

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - "*.nix"
  - flake.lock
  - bin/
