title: catstret.ch
baseurl: ""
url: "https://catstret.ch"
permalink: "/:year:month/:title/"
excerpt_separator: <!--cut-->
future: true

kramdown:
  parse_block_html: true
  hard_wrap: false
  gfm_quirks:
    - paragraph_end

plugins:
  - jekyll-feed

collections:
  snippets:
    permalink: "/snippets/:name:output_ext"
    output: true
  post_tags:
    permalink: "/tag/:name/"
    output: true

defaults:
  - scope:
      path: ''
      type: post_tags
    values:
      permalink: "/tag/:name/"
      layout: post_tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - flake.nix
  - shell.nix
  - flake.lock
  - bin/
